### ISSUE TITLE
PLAY not emitting sound nor pausing

### ISSUE THREAD

**Issue by mdasoh** [tkchia/GW-BASIC#2] opened 2020-06-06 16:30 UTC
there's a PLAY example here:  https://hwiegman.home.xs4all.nl/gw-man/PLAYN.html
also note that the following can pause for one second (though it does turn on the speaker):
<pre>
10 PLAY "p1"
</pre>
nearly as I can see, PLAY is not yet implemented.

**Comment by tkchia** [comment] 2020-06-07 05:45
Hello @mdasoh,

> early as I can see, PLAY is not yet implemented.

Yes.  One problem is `PLAY` (and `SOUND`) are quite tricky to implement, since sounds are allowed to play in the background while other stuff continue to happen.

The sound functionality _is_ included in the [MS-DOS v1.25](https://github.com/microsoft/MS-DOS/tree/master/v1.25/bin) `BASICA.COM` binary, which is now MIT-licensed, so there is a possibility of adding it into `OEM.ASM`.  It involves quite a lot of code though --- it even tries to intercept IRQ 0 and reprogram its frequency (!!).

Thank you!

**Comment by mdasoh** [comment] 2020-06-07 14:49
there's a pretty concise explanation of how to do that in sound.txt of pc game programmer's encyclopedia, http://show.ing.me/pcgpe10a.zip and a more involved explanation the operating systems dev wiki at https://wiki.osdev.org/PIT

**Comment by tkchia** [comment] 2020-06-08 13:52
Hello @mdasoh,

I have come up with a (hopefully) working implementation: https://github.com/tkchia/GW-BASIC/commit/16b5ebf15086c772e4971f6ffe36f619bb172d70 .  Thank you!

**Comment by tkchia** [comment] 2020-06-09 12:45
@mdasoh: let me know if `PLAY` works for you now.  Thank you!

**Comment by mdasoh** [comment] 2020-06-09 15:29
It is working pretty well, I want to say it's working about as well as gwbasic.exe  Well, one difference is that the gwbasic I had supports IF PLAY(0) = N where N is a number.  I'm not sure if yours is supposed to, however.  When I import the following files to my 386, they fail to complete PLAY before the program terminates:
PLAID2.BAS :
<pre>
30 PLAY "MBABCDABCDABCD"
200 PLAY "MBCDEFCDEF"
300 PLAY "p1"
400 PLAY "p1"
410 SYSTEM
</pre>
PLAID.BAS :
<pre>
30 PLAY "MBABCDABCDABCD"
40 IF PLAY( 0 ) = 4 THEN 200
50 GOTO 40
200 PLAY "MBCDEFCDEF"
300 PLAY "p1"
400 PLAY "p1"
410 SYSTEM
</pre>
and PLAY.BAT :
<pre>
gwtkch04 plaid2     <-- I hear six notes from line 30
gwbasic plaid       <-- I hear seven notes from line 30
gwbasic plaid2      <-- I hear five notes from line 30
</pre>

**Comment by tkchia** [comment] 2020-06-09 16:30
Hello @mdasoh,

> Well, one difference is that the gwbasic I had supports IF PLAY(0) = N where N is a number. I'm not sure if yours is supposed to, however.

Thanks for your feedback.  Well, it does seem that this 1983 version of GW-BASIC simply lacks support for `PLAY( )` as a function.

(I would guess that other old versions of GW-BASIC or `BASICA.COM` also do not support it, but I will probably need to check to confirm.)

> When I import the following files to my 386, they fail to complete PLAY before the program terminates:

I think that is to be expected, and is probably not a bug.  `"MB"` says to play the notes in the background, i.e. allow GW-BASIC to do other things while playing the notes.  So a `SYSTEM` command will likely cut off whatever music happens to be playing.

Switching to foreground mode (`"MF"`), e.g.
```
300 PLAY "MFP1"
```
should allow all the notes --- and the pauses --- to be played all the way to completion.

Thank you!

**Comment by mdasoh** [comment] 2020-06-09 16:38
prefixing all the play statements listed above with MF instead of MB I observe the following on the 386:
1. 5 notes from line 30
2. all 12 notes on line 30, and then it gets stuck and I have to ^break and type SYSTEM
3. 5 notes from line 30

**Comment by tkchia** [comment] 2020-06-09 16:48
Hello @mdasoh,

Is this the modified `plaid2.bas` program you are trying with both GW-BASICs?
```
30 PLAY "MFABCDABCDABCD"
200 PLAY "MFCDEFCDEF"
300 PLAY "p1"
400 PLAY "p1"
410 SYSTEM
```
Thank you!

**Comment by mdasoh** [comment] 2020-06-09 16:53
<pre>
30 PLAY "MFABCDABCDABCD"
200 PLAY "MFCDEFCDEF"
300 PLAY "MFp1"
400 PLAY "MFp1"
410 SYSTEM
</pre>

**Comment by tkchia** [comment] 2020-06-09 16:58
Hello @mdasoh,

Both GW-BASICs should play _all_ 20 notes and both pauses.  Perhaps you can check if you transferred the modified `plaid2.bas` correctly onto your 386?  Thank you!

**Comment by mdasoh** [comment] 2020-06-09 17:12
and, you are correct.  here is the garbage program, which GWtkch04.EXE did not save correctly with SAVE"plaid2.bas",a
<pre>
30 PLAY "MBABCDABCDABCD"
200 PLAY "MBCDEFCDEF"
300 PLAY "p1"
400 PLAY "p1"
410 SYSTEM
Z00 PLAY "p1"
400 PLAY "p1"
^Z@@@@@@
</pre>
sorry about that comment on the pauses, I seem to remember changing them.

**Comment by mdasoh** [comment] 2020-06-09 17:17
it seems I had not done "sudo" when copying the file.

**Comment by tkchia** [comment] 2020-06-09 17:18
Hello @mdasoh,

Thanks for your report.  Anyway, if there are any bugs in the `SAVE "`...`", A` command --- and they are reproducible --- I suppose I would like to know about them as well.

Thank you!

**Comment by mdasoh** [comment] 2020-06-09 17:19
Probably just has to do with the length of the file saved.

**Comment by tkchia** [comment] 2020-06-10 10:08
Hello @mdasoh,

Thanks.  Since `PLAY` (the command) now seems to be working on your end, I guess I can proceed to close this.

Thank you!

**Closed by tkchia** 2020-06-10 10:08 UTC
